services:
  api:
    image: viakable-backend:latest
    ports:
      - "7000:7000"
    depends_on:
      - db

  db:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
