"""all tables

Revision ID: 6046fcfd31a8
Revises: 
Create Date: 2024-08-21 15:09:37.910453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6046fcfd31a8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('materials',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('unit', sa.String(length=60), nullable=False),
    sa.Column('color', sa.String(length=60), nullable=True),
    sa.Column('image', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('isActive', sa.Boolean(), nullable=False),
    sa.Column('isSuperUser', sa.Boolean(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('modifiedAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_operator', sa.Integer(), nullable=False),
    sa.Column('id_forklift', sa.Integer(), nullable=False),
    sa.Column('creation_datetime', sa.DateTime(), nullable=False),
    sa.Column('estimate_datetime', sa.DateTime(), nullable=False),
    sa.Column('order_datetime', sa.DateTime(), nullable=True),
    sa.Column('state', sa.String(length=60), nullable=False),
    sa.Column('canceled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_forklift'], ['users.id'], ),
    sa.ForeignKeyConstraint(['id_operator'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role_by_user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_role', sa.String(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_role'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('admins',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('firstName', sa.String(), nullable=False),
    sa.Column('lastName', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['role_by_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('forklifts',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['role_by_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('material_by_order',
    sa.Column('id_material', sa.Integer(), nullable=False),
    sa.Column('id_order', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_material'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['id_order'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id_material', 'id_order')
    )
    op.create_table('operators',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('machine', sa.String(), nullable=False),
    sa.Column('area', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['role_by_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('operators')
    op.drop_table('material_by_order')
    op.drop_table('forklifts')
    op.drop_table('admins')
    op.drop_table('role_by_user')
    op.drop_table('orders')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_table('materials')
    # ### end Alembic commands ###
