"""new tables

Revision ID: ee8311233f5e
Revises: 
Create Date: 2024-08-20 20:21:48.206378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee8311233f5e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('isActive', sa.Boolean(), nullable=False),
    sa.Column('isSuperUser', sa.Boolean(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('modifiedAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('role_by_user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_role', sa.String(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_role'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('admins',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('firstName', sa.String(), nullable=False),
    sa.Column('lastName', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['role_by_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('forklifts',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['role_by_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('operators',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('machine', sa.String(), nullable=False),
    sa.Column('area', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['role_by_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('operators')
    op.drop_table('forklifts')
    op.drop_table('admins')
    op.drop_table('role_by_user')
    op.drop_table('users')
    op.drop_table('roles')
    # ### end Alembic commands ###
